/**
 * X-Twilio-Signature verification.
 *
 * ==========================================================================
 * THE ORACLE IS TWILIO'S OWN SDK, NOT A CONSTANT COPIED OUT OF A DOC.
 * ==========================================================================
 * An implementation tested only against itself proves that the two halves of
 * one function agree - which is exactly what a WRONG algorithm also proves.
 * So the primary assertion here computes the signature twice: once with our
 * nine-line implementation and once with `twilio/lib/webhooks/webhooks`, the
 * code Twilio ships and the closest thing to the code that signs the real
 * request. They must agree.
 *
 * WHY WE DO NOT SIMPLY CALL THE SDK IN PRODUCTION. clients.ts imports the
 * Twilio SDK LAZILY and only on the live send path, so a sandbox deploy loads
 * no provider code at all. A webhook that imported it at module scope would
 * pull the SDK into every request touching the route. The SDK is a test
 * dependency here and stays out of the request path.
 *
 * THE PINNED VECTOR BELOW WAS PRODUCED BY THAT SDK, in this repo, at this
 * version - it is not remembered and not transcribed. It exists so the suite
 * still fails if BOTH implementations are changed together.
 */
import { afterEach, describe, expect, it } from "vitest";
import { getExpectedTwilioSignature } from "twilio/lib/webhooks/webhooks";

import {
  computeTwilioSignature,
  signedRequestUrl,
  verifyTwilioSignature,
} from "./inbound-signature";

const TOKEN = "12345";
const URL_ = "https://mycompany.com/myapp.php?foo=1&bar=2";
const PARAMS = {
  Digits: "1234",
  To: "+18005551212",
  From: "+14158675310",
  Caller: "+14158675310",
  CallSid: "CA1234567890ABCDE",
};
/** Generated by the Twilio SDK for (TOKEN, URL_, PARAMS). See the header. */
const EXPECTED = "GvWf1cFY/Q7PnoempGyD5oXAezc=";

describe("computeTwilioSignature", () => {
  it("AGREES WITH THE TWILIO SDK — the differential assertion", () => {
    expect(computeTwilioSignature(TOKEN, URL_, PARAMS)).toBe(
      getExpectedTwilioSignature(TOKEN, URL_, PARAMS),
    );
  });

  it("agrees with the SDK on a realistic inbound-SMS payload too", () => {
    // The shape this route actually receives: a PT reply to the 24h reminder.
    // One vector can agree by accident; two of different shapes do not.
    // The two Sid fields are DELIBERATELY not shaped like real Twilio ids.
    // GitHub push protection reads `AC` + 32 hex as a Twilio Account String
    // Identifier and refuses the push - correctly, since it cannot know a
    // fixture from a leak. The signature is a hash over whatever strings are
    // here, so their shape is irrelevant to what this test proves, and a
    // fixture that cannot be mistaken for a credential is worth more than one
    // that looks authentic.
    const inbound = {
      MessageSid: "SM-not-a-real-sid-fixture",
      AccountSid: "AC-not-a-real-sid-fixture",
      From: "+351912345678",
      To: "+351210000000",
      Body: "Sim",
      NumMedia: "0",
    };
    const url = "https://app.osteojp.pt/api/webhooks/twilio/inbound";
    expect(computeTwilioSignature("some-auth-token", url, inbound)).toBe(
      getExpectedTwilioSignature("some-auth-token", url, inbound),
    );
  });

  it("matches the pinned vector, so both implementations cannot drift together", () => {
    expect(computeTwilioSignature(TOKEN, URL_, PARAMS)).toBe(EXPECTED);
  });

  it("is INDEPENDENT of the order the params arrive in", () => {
    // Twilio sorts by key before concatenating. A form-parsing change that
    // altered iteration order must not alter the signature.
    const reversed = Object.fromEntries(Object.entries(PARAMS).reverse());
    expect(computeTwilioSignature(TOKEN, URL_, reversed)).toBe(EXPECTED);
  });

  it("changes when the URL changes", () => {
    expect(computeTwilioSignature(TOKEN, URL_ + "&x=1", PARAMS)).not.toBe(EXPECTED);
  });

  it("changes when ANY param value changes", () => {
    expect(computeTwilioSignature(TOKEN, URL_, { ...PARAMS, Digits: "1235" })).not.toBe(EXPECTED);
  });

  it("changes when the auth token changes", () => {
    expect(computeTwilioSignature("12346", URL_, PARAMS)).not.toBe(EXPECTED);
  });
});

describe("verifyTwilioSignature", () => {
  it("accepts the signature Twilio would have sent", () => {
    expect(
      verifyTwilioSignature({ authToken: TOKEN, url: URL_, params: PARAMS, signature: EXPECTED }),
    ).toBe(true);
  });

  it("REFUSES an absent header rather than throwing", () => {
    // A missing header is what an unsigned probe of the endpoint looks like.
    // It must be a plain false, not a 500 that reveals the route is real.
    expect(
      verifyTwilioSignature({ authToken: TOKEN, url: URL_, params: PARAMS, signature: null }),
    ).toBe(false);
  });

  it("REFUSES a signature of the wrong length without throwing", () => {
    // `timingSafeEqual` throws on a length mismatch. Left unguarded, a
    // truncated header would 500 - and a 500 that only happens for one length
    // is itself an oracle.
    for (const sig of ["", "x", EXPECTED.slice(0, -1), EXPECTED + "="]) {
      expect(() =>
        verifyTwilioSignature({ authToken: TOKEN, url: URL_, params: PARAMS, signature: sig }),
      ).not.toThrow();
      expect(
        verifyTwilioSignature({ authToken: TOKEN, url: URL_, params: PARAMS, signature: sig }),
      ).toBe(false);
    }
  });

  it("REFUSES a correctly-shaped signature over different content", () => {
    // The forgery that matters: same length, valid base64, wrong body.
    const other = computeTwilioSignature(TOKEN, URL_, { ...PARAMS, From: "+351912345678" });
    expect(other).toHaveLength(EXPECTED.length);
    expect(
      verifyTwilioSignature({ authToken: TOKEN, url: URL_, params: PARAMS, signature: other }),
    ).toBe(false);
  });
});

describe("signedRequestUrl", () => {
  const saved = process.env.REMINDERS_INBOUND_BASE_URL;
  afterEach(() => {
    if (saved === undefined) delete process.env.REMINDERS_INBOUND_BASE_URL;
    else process.env.REMINDERS_INBOUND_BASE_URL = saved;
  });

  it("builds the configured origin plus the path", () => {
    process.env.REMINDERS_INBOUND_BASE_URL = "https://app.osteojp.pt";
    expect(signedRequestUrl("/api/webhooks/twilio/inbound")).toBe(
      "https://app.osteojp.pt/api/webhooks/twilio/inbound",
    );
  });

  it("tolerates a trailing slash on the configured origin", () => {
    process.env.REMINDERS_INBOUND_BASE_URL = "https://app.osteojp.pt/";
    expect(signedRequestUrl("/api/webhooks/twilio/inbound")).toBe(
      "https://app.osteojp.pt/api/webhooks/twilio/inbound",
    );
  });

  it("returns null when unset — it does not guess an origin", () => {
    // A guessed origin produces a signature over a string Twilio never signed,
    // so every legitimate request would fail. Refusing loudly is the only safe
    // unset behaviour.
    delete process.env.REMINDERS_INBOUND_BASE_URL;
    expect(signedRequestUrl("/api/webhooks/twilio/inbound")).toBeNull();
    process.env.REMINDERS_INBOUND_BASE_URL = "   ";
    expect(signedRequestUrl("/api/webhooks/twilio/inbound")).toBeNull();
  });
});

describe("the route does not trust forwarded headers for the signed URL", () => {
  const SRC = readFileSyncStripped("inbound-signature.ts");

  it("never reads x-forwarded-host or x-forwarded-proto", () => {
    // Both are attacker-controllable on an open route. Signing over a host the
    // caller chose lets them produce a matching signature for any content.
    expect(SRC).not.toMatch(/x-forwarded-host/i);
    expect(SRC).not.toMatch(/x-forwarded-proto/i);
  });
});

function readFileSyncStripped(name: string): string {
  /* eslint-disable @typescript-eslint/no-require-imports */
  const { readFileSync } = require("node:fs") as typeof import("node:fs");
  const { join } = require("node:path") as typeof import("node:path");
  /* eslint-enable @typescript-eslint/no-require-imports */
  return readFileSync(join(__dirname, name), "utf8")
    .replace(/\/\*[\s\S]*?\*\//g, "")
    .replace(/^\s*\/\/.*$/gm, "");
}
